// Blog post titles/excerpts and the landing-page cause cards.
export const STORIES = {
  // ── Featured post ──
  "Inside Cross River: How Community Rangers Are Guarding Nigeria's Last Rainforest": { Igbo: "N'ime Cross River: Otu Ndị Nche Obodo Si Echekwa Oke Ọhịa Ikpeazụ Naijirịa", Yoruba: "Nínú Cross River: Bí Àwọn Ẹ̀ṣọ́ Àdúgbò Ṣe Ń Ṣọ́ Igbó Ìkẹyìn Nàìjíríà", French: "Au cœur de Cross River : comment les gardes communautaires protègent la dernière forêt tropicale du Nigéria" },
  "In the hills of Cross River State, a new generation of community rangers is proving that the most effective way to protect a forest is to hand its stewardship back to the people who live in it. We spent a week on patrol with them.": { Igbo: "N'ugwu Steeti Cross River, ọgbọ ọhụrụ nke ndị nche obodo na-egosi na ụzọ kacha mma ichekwa ọhịa bụ inyeghachi ndị bi na ya ọrụ nlekọta. Anyị soro ha nọrọ otu izu na nlegharị anya.", Yoruba: "Ní àwọn òkè Ìpínlẹ̀ Cross River, ìran tuntun àwọn ẹ̀ṣọ́ àdúgbò ń fi hàn pé ọ̀nà tí ó dára jùlọ láti dáàbò bo igbó ni láti fi ìtọ́jú rẹ̀ lé àwọn tí ń gbé inú rẹ̀ lọ́wọ́. A lo ọ̀sẹ̀ kan pẹ̀lú wọn.", French: "Dans les collines de l'État de Cross River, une nouvelle génération de gardes communautaires démontre que la meilleure façon de protéger une forêt est d'en confier la gestion à ceux qui y vivent. Nous avons passé une semaine en patrouille avec eux." },

  // ── Post titles ──
  "Why Native Species Matter in Coastal Reforestation": { Igbo: "Ihe Mere Ụdị Osisi Obodo Ji Dị Mkpa N'ịkụ Osisi N'ụsọ Oké Osimiri", Yoruba: "Ìdí Tí Àwọn Ẹ̀dá Ìbílẹ̀ Fi Ṣe Pàtàkì Nínú Ìdálẹ́ Igbó Létí Òkun", French: "Pourquoi les espèces indigènes comptent dans le reboisement côtier" },
  "What Clean Water Really Costs a Rural Community": { Igbo: "Ihe Mmiri Dị Ọcha Na-efu Obodo Ime N'ezie", Yoruba: "Ohun Tí Omi Mímọ́ Ń Ná Àdúgbò Ìgbèríko Ní Tòótọ́", French: "Ce que l'eau potable coûte vraiment à une communauté rurale" },
  "The Harmattan Is Changing — and Northern Farmers Noticed First": { Igbo: "Ugụrụ Na-agbanwe — Ndị Ọrụ Ugbo Ugwu Bụ Ndị Buru Ụzọ Hụ Ya", Yoruba: "Òyé Ń Yípadà — Àwọn Àgbẹ̀ Àríwá Ni Wọ́n Kọ́kọ́ Kíyèsí", French: "L'harmattan change — et les agriculteurs du Nord l'ont remarqué en premier" },
  "School Farms Are Teaching More Than Agriculture": { Igbo: "Ubi Ụlọ Akwụkwọ Na-akụzi Ihe Karịrị Ọrụ Ugbo", Yoruba: "Oko Ilé-ìwé Ń Kọ́ni Ju Iṣẹ́ Àgbẹ̀ Lọ", French: "Les fermes scolaires enseignent bien plus que l'agriculture" },
  "Reading Nigeria's Climate Act: What It Means for Local Projects": { Igbo: "Ịgụ Iwu Ihu Igwe Naijirịa: Ihe Ọ Pụtara Maka Ọrụ Obodo", Yoruba: "Kíka Òfin Ojú-ọjọ́ Nàìjíríà: Ohun Tí Ó Túmọ̀ Sí fún Iṣẹ́ Ìbílẹ̀", French: "Lire la loi climat du Nigéria : ce qu'elle signifie pour les projets locaux" },
  "Wildlife Corridors: Giving Animals Room to Move": { Igbo: "Ụzọ Anụ Ọhịa: Inye Anụ Ohere Ịgagharị", Yoruba: "Ọ̀nà Ẹranko Ìgbẹ́: Fífún Ẹranko Ní Àyè Láti Rìn", French: "Corridors fauniques : laisser aux animaux la place de circuler" },
  "Turning Waste Into Work in Lagos": { Igbo: "Ime Ka Ahịhịa Bụrụ Ọrụ Na Legos", Yoruba: "Yíyí Ìdọ̀tí Padà Sí Iṣẹ́ Ní Èkó", French: "Transformer les déchets en emplois à Lagos" },
  "Wetlands Are Nigeria's Cheapest Flood Defence": { Igbo: "Ala Mmiri Bụ Mgbochi Idei Mmiri Kacha Dị Ọnụ Ala Na Naijirịa", Yoruba: "Ilẹ̀ Ọlọ́mi Ni Ààbò Ìkún Omi Tí Ó Rọrùn Jùlọ Ní Nàìjíríà", French: "Les zones humides, la défense anti-inondation la moins chère du Nigéria" },
  "Solar Beyond the Panel: Why Maintenance Training Comes First": { Igbo: "Anyanwụ Karịa Mbadamba: Ihe Mere Ọzụzụ Nlekọta Ji Buru Ụzọ", Yoruba: "Oòrùn Ju Pánẹ́ẹ̀lì Lọ: Ìdí Tí Ẹ̀kọ́ Ìtọ́jú Fi Ṣáájú", French: "Le solaire au-delà du panneau : pourquoi la formation à l'entretien vient d'abord" },
  "Volunteering Changed How I See My Own Street": { Igbo: "Ọrụ Afọ Ofufo Gbanwere Otu M Si Ele Okporo Ámá M Anya", Yoruba: "Iṣẹ́ Olùrànlọ́wọ́ Yí Bí Mo Ṣe Ń Wo Ìgboro Ara Mi Padà", French: "Le bénévolat a changé mon regard sur ma propre rue" },
  "Land Rights Are Climate Rights": { Igbo: "Ikike Ala Bụ Ikike Ihu Igwe", Yoruba: "Ẹ̀tọ́ Ilẹ̀ Ni Ẹ̀tọ́ Ojú-ọjọ́", French: "Les droits fonciers sont des droits climatiques" },
  "Field Notes: A Season of Regreening in Katsina": { Igbo: "Ndetu Ọrụ Ubi: Oge Iweghachi Ndụ Na Katsina", Yoruba: "Àkọsílẹ̀ Pápá: Àkókò Ìsọdọ̀tun Ní Katsina", French: "Notes de terrain : une saison de reverdissement à Katsina" },

  // ── Post excerpts ──
  "Planting the wrong tree can do more harm than planting none at all. Here is how we choose species for the shorelines of Ondo and Lagos.": { Igbo: "Ịkụ osisi na-ekwesịghị ekwesị nwere ike imebi karịa ịkụghị ya ma ọlị. Nke a bụ otu anyị si ahọrọ ụdị osisi maka ụsọ mmiri Ondo na Legos.", Yoruba: "Gbígbin igi tí kò yẹ lè ṣe ìbàjẹ́ ju kí a má gbin rárá lọ. Èyí ni bí a ṣe ń yan ẹ̀dá fún etíkun Ondó àti Èkó.", French: "Planter le mauvais arbre peut faire plus de mal que de ne rien planter. Voici comment nous choisissons les espèces pour les littoraux d'Ondo et de Lagos." },
  "A borehole is only the beginning. We break down the maintenance, training, and local ownership that keep water flowing years after the drilling rig leaves.": { Igbo: "Olulu mmiri bụ naanị mmalite. Anyị na-akọwa nlekọta, ọzụzụ, na nwe obodo nke na-eme ka mmiri na-eru afọ ọtụtụ mgbe ngwa igwu ala hapụsịrị.", Yoruba: "Kànga jẹ́ ìbẹ̀rẹ̀ nìkan. A ṣàlàyé ìtọ́jú, ẹ̀kọ́, àti ohun ìní ìbílẹ̀ tí ó ń mú omi ṣàn fún ọdún púpọ̀ lẹ́yìn tí ẹ̀rọ ìwalẹ̀ bá kúrò.", French: "Un forage n'est qu'un début. Nous détaillons l'entretien, la formation et l'appropriation locale qui font couler l'eau des années après le départ de la foreuse." },
  "Long before the data confirmed it, farmers in Sokoto and Katsina were adjusting their planting calendars. Their observations are now shaping our regreening work.": { Igbo: "Ogologo oge tupu data akwadoo ya, ndị ọrụ ugbo na Sokoto na Katsina na-agbanwe kalenda ịkụ mkpụrụ ha. Ihe ha hụrụ na-eduzi ọrụ mweghachi ndụ anyị ugbu a.", Yoruba: "Kí data tó jẹ́rìí sí i, àwọn àgbẹ̀ ní Sokoto àti Katsina ti ń ṣàtúnṣe àkókò gbígbin wọn. Ohun tí wọ́n rí ni ó ń darí iṣẹ́ ìsọdọ̀tun wa báyìí.", French: "Bien avant que les données ne le confirment, les agriculteurs de Sokoto et Katsina ajustaient leurs calendriers de plantation. Leurs observations orientent désormais notre travail de reverdissement." },
  "Students who grow their own food learn patience, nutrition, and climate science in one plot of land. A look at what happens after the first harvest.": { Igbo: "Ụmụ akwụkwọ na-akụ nri nke ha na-amụta ndidi, nri bara uru, na sayensị ihu igwe n'otu ala. Lee ihe na-eme mgbe owuwe ihe ubi mbụ gasịrị.", Yoruba: "Àwọn akẹ́kọ̀ọ́ tí wọ́n ń gbin oúnjẹ ara wọn ń kọ́ sùúrù, ìjẹ́mọ́ oúnjẹ, àti ìmọ̀ ojú-ọjọ́ ní ilẹ̀ kan. Wo ohun tí ó ń ṣẹlẹ̀ lẹ́yìn ìkórè àkọ́kọ́.", French: "Les élèves qui cultivent leur nourriture apprennent la patience, la nutrition et la science du climat sur une seule parcelle. Regard sur ce qui suit la première récolte." },
  "Policy documents rarely reach the communities they affect. We translate the parts that matter for anyone running an environmental project on the ground.": { Igbo: "Akwụkwọ iwu anaghị eruru obodo ọ na-emetụta aka. Anyị na-atụgharị akụkụ ndị dị mkpa maka onye ọ bụla na-arụ ọrụ gburugburu n'ala.", Yoruba: "Àwọn ìwé òfin kì í dé ọ̀dọ̀ àwọn àdúgbò tí ó kàn. A ṣàlàyé àwọn apá tí ó ṣe pàtàkì fún ẹnikẹ́ni tí ń ṣiṣẹ́ àyíká ní ìpìlẹ̀.", French: "Les textes de loi atteignent rarement les communautés concernées. Nous traduisons les passages qui comptent pour quiconque mène un projet environnemental sur le terrain." },
  "Fragmented habitat is a quiet driver of species loss. Connecting the pieces in Enugu and Ebonyi may matter more than protecting any single reserve.": { Igbo: "Ebe obibi kewara ekewa bụ ihe na-akpata ọnwụ ụdị anụ n'ụzọ jụụ. Ijikọta ha na Enugwu na Ebonyi nwere ike ịdị mkpa karịa ichekwa otu ebe nchekwa.", Yoruba: "Ibùgbé tí ó pín sí wẹ́wẹ́ ni ó ń fa ìparun ẹ̀dá ní ìdákẹ́jẹ́ẹ́. Sísopọ̀ wọn ní Enugu àti Ebonyi lè ṣe pàtàkì ju dídáàbò bo ibi ìpamọ́ kan lọ.", French: "La fragmentation des habitats est un moteur silencieux de la perte d'espèces. Relier les fragments à Enugu et Ebonyi compte peut-être plus que protéger une seule réserve." },
  "Compost, biogas, and recycled plastic are creating livelihoods in neighbourhoods where refuse used to pile up. Meet the people running the sorting sheds.": { Igbo: "Fatịlaịza, gas okike, na plastik emeghachiri na-eweta ihe ndụ n'ógbè ebe ahịhịa na-adịbu ukwuu. Zute ndị na-elekọta ụlọ nkewa.", Yoruba: "Ajílẹ̀, gáàsì àdánidá, àti ike àtúnlò ń pèsè ọ̀nà ìgbésí ayé ní àwọn àdúgbò tí ìdọ̀tí ti máa ń kójọ. Pàdé àwọn tí ń darí ilé ìyàsọ́tọ̀.", French: "Compost, biogaz et plastique recyclé créent des moyens de subsistance là où les ordures s'entassaient. Rencontre avec ceux qui font tourner les centres de tri." },
  "The Niger Delta's wetlands filter water, store carbon, and absorb floodwater for free. Restoring them costs a fraction of the concrete alternative.": { Igbo: "Ala mmiri Niger Delta na-asacha mmiri, na-echekwa carbon, ma na-amịkọrọ mmiri idei n'efu. Iweghachi ha na-efu obere ego karịa iji simenti.", Yoruba: "Ilẹ̀ ọlọ́mi Niger Delta ń sẹ́ omi, ń tọ́jú carbon, ó sì ń fa omi ìkún mọ́ra lọ́fẹ̀ẹ́. Mímú wọn padà kò wọ́n bí lílo símẹ́ǹtì.", French: "Les zones humides du delta du Niger filtrent l'eau, stockent le carbone et absorbent les crues gratuitement. Les restaurer coûte une fraction du prix du béton." },
  "Installed systems fail without local technicians. In rural Niger State, we train before we build — and the lights stay on.": { Igbo: "Usoro etinyere na-ada ma ọ bụrụ na e nweghị ndị ọrụ nka obodo. N'ime obodo Steeti Niger, anyị na-azụ tupu anyị arụọ — ọkụ na-adịgidekwa.", Yoruba: "Ètò tí a fi sí i máa ń kùnà láìsí àwọn oníṣẹ́ ọwọ́ ìbílẹ̀. Ní ìgbèríko Ìpínlẹ̀ Niger, a kọ́ni kí a tó kọ́ — iná sì ń tàn nìṣó.", French: "Les installations tombent en panne sans techniciens locaux. Dans l'État rural du Niger, nous formons avant de construire — et la lumière reste allumée." },
  "A volunteer from Ibadan writes about her first tree-planting weekend, and the habit it started long after the shovels were returned.": { Igbo: "Otu onye ọrụ afọ ofufo si Ibadan na-ede banyere izu ụka mbụ ọ kụrụ osisi, na omume ọ malitere ogologo oge ka e weghachiri shọvel.", Yoruba: "Olùrànlọ́wọ́ kan láti Ìbàdàn kọ̀wé nípa ọ̀sẹ̀ àkọ́kọ́ tí ó gbin igi, àti ìwà tí ó bẹ̀rẹ̀ lẹ́yìn tí a ti dá ọkọ́ padà.", French: "Une bénévole d'Ibadan raconte son premier week-end de plantation, et l'habitude née bien après le retour des pelles." },
  "When communities hold secure title to their land, forests stand a better chance. A look at our legal support work in Taraba.": { Igbo: "Mgbe obodo nwere ikike ala siri ike, ọhịa na-enwe ohere ka mma. Lee ọrụ nkwado iwu anyị na Taraba.", Yoruba: "Nígbà tí àwọn àdúgbò bá ní ẹ̀tọ́ ilẹ̀ tí ó dájú, igbó ní àǹfààní tí ó dára jù. Wo iṣẹ́ ìtìlẹ́yìn òfin wa ní Taraba.", French: "Quand les communautés détiennent un titre foncier sûr, les forêts s'en portent mieux. Regard sur notre appui juridique à Taraba." },
  "Photographs and observations from six months of farmer-managed natural regeneration, where the trees were already in the soil, waiting.": { Igbo: "Foto na ihe anyị hụrụ n'ọnwa isii nke mweghachi okike ndị ọrụ ugbo na-elekọta, ebe osisi dịbu n'ala, na-echere.", Yoruba: "Àwòrán àti ìṣàkíyèsí láti oṣù mẹ́fà ìsọdọ̀tun àdánidá tí àwọn àgbẹ̀ ń darí, níbi tí igi ti wà nínú ilẹ̀ tẹ́lẹ̀, tí ń dúró.", French: "Photographies et observations de six mois de régénération naturelle assistée, là où les arbres étaient déjà dans le sol, en attente." },

  // ── Landing cause cards ──
  "Plant Tree, Save Earth & Lives Secure the Future": { Igbo: "Kụọ Osisi, Zọpụta Ụwa na Ndụ, Chekwaa Ọdịnihu", Yoruba: "Gbin Igi, Gba Ayé àti Ẹ̀mí Là, Dáàbò Bo Ọjọ́ Iwájú", French: "Planter des arbres, sauver la Terre et des vies, préserver l'avenir" },
  "Tree planting is an essential action in combating deforestation and climate change. Every tree we plant helps absorb carbon dioxide, purifies the air, and supports wildlife habitats. By taking small steps to protect and restore our planet, we are investing in a healthier, more sustainable future for generations to come.": { Igbo: "Ịkụ osisi bụ ihe dị mkpa n'ịlụso igbutu ọhịa na mgbanwe ihu igwe ọgụ. Osisi ọ bụla anyị kụrụ na-enyere aka ịmịkọrọ carbon dioxide, na-asacha ikuku, ma na-akwado ebe obibi anụ ọhịa. Site n'ime obere nzọụkwụ, anyị na-etinye ego n'ọdịnihu ka mma maka ọgbọ na-abịa.", Yoruba: "Gbígbin igi ṣe pàtàkì nínú ìjà lòdì sí ìdálẹ́ igbó àti ìyípadà ojú-ọjọ́. Gbogbo igi tí a gbin ń fa carbon dioxide mọ́ra, ó ń sọ afẹ́fẹ́ di mímọ́, ó sì ń ṣàtìlẹ́yìn fún ibùgbé ẹranko ìgbẹ́. Nípa ìgbésẹ̀ kékeré, à ń fi owó sí ọjọ́ iwájú tí ó dára fún àwọn ìran tí ń bọ̀.", French: "La plantation d'arbres est essentielle pour lutter contre la déforestation et le changement climatique. Chaque arbre planté absorbe le dioxyde de carbone, purifie l'air et soutient les habitats sauvages. Par de petits gestes, nous investissons dans un avenir plus sain et plus durable." },
  "Advocating for School Farms: Educating the Grassroots for a Sustainable Future": { Igbo: "Ịkwado Ubi Ụlọ Akwụkwọ: Ịkụziri Ndị Obodo Maka Ọdịnihu Na-adigide", Yoruba: "Ìgbéjàko fún Oko Ilé-ìwé: Kíkọ́ Àwọn Ìpìlẹ̀ fún Ọjọ́ Iwájú Alálòpẹ́", French: "Plaider pour les fermes scolaires : éduquer la base pour un avenir durable" },
  "School farms are powerful tools for educating students about sustainable agriculture, food systems, and environmental stewardship. By advocating for and supporting school farm programs, we can empower the next generation with hands-on learning experiences that foster a deeper connection to nature, promote healthy eating habits, and inspire future leaders in sustainability.": { Igbo: "Ubi ụlọ akwụkwọ bụ ngwá ọrụ dị ike maka ịkụziri ụmụ akwụkwọ banyere ọrụ ugbo na-adigide, usoro nri, na nlekọta gburugburu. Site n'ịkwado mmemme ubi ụlọ akwụkwọ, anyị nwere ike inye ọgbọ na-abịa ike site na mmụta aka ọrụ nke na-eme ka ha nwekwuo njikọ na okike.", Yoruba: "Oko ilé-ìwé jẹ́ ohun èlò tí ó lágbára fún kíkọ́ àwọn akẹ́kọ̀ọ́ nípa àgbẹ̀ alálòpẹ́, ètò oúnjẹ, àti ìtọ́jú àyíká. Nípa ìtìlẹ́yìn fún ètò oko ilé-ìwé, a lè fún ìran tí ń bọ̀ lágbára pẹ̀lú ẹ̀kọ́ àṣeṣe tí ó ń mú ìsopọ̀ pẹ̀lú ìṣẹ̀dá jinlẹ̀.", French: "Les fermes scolaires sont de puissants outils pour enseigner l'agriculture durable, les systèmes alimentaires et la gestion de l'environnement. En les soutenant, nous donnons à la prochaine génération une expérience pratique qui nourrit un lien plus profond avec la nature." },
  "People that Need Clean Drinking Water": { Igbo: "Ndị Chọrọ Mmiri Ọñụñụ Dị Ọcha", Yoruba: "Àwọn Tí Wọ́n Nílò Omi Mímu Mímọ́", French: "Des personnes qui ont besoin d'eau potable" },
  "Access to clean drinking water is a basic human right, yet millions around the world still lack this vital resource. Contaminated water leads to preventable diseases and countless lives lost every year. By improving water infrastructure and supporting sustainable water management practices, we can ensure safe water for all, safeguarding health and fostering communities' growth and well-being.": { Igbo: "Inweta mmiri ọñụñụ dị ọcha bụ ikike mmadụ, ma ọtụtụ nde mmadụ ka na-enweghị ya. Mmiri rụrụ arụ na-eweta ọrịa a pụrụ igbochi na ọnwụ ọtụtụ mmadụ kwa afọ. Site n'ịkwalite akụrụngwa mmiri na ịkwado njikwa mmiri na-adigide, anyị nwere ike ihu na onye ọ bụla nwere mmiri dị mma.", Yoruba: "Rírí omi mímu mímọ́ jẹ́ ẹ̀tọ́ ọmọnìyàn, síbẹ̀ àràádọ́ta ọ̀kẹ́ ènìyàn ṣì kò ní i. Omi tí ó díbàjẹ́ ń fa àrùn tí a lè dènà àti ikú ọ̀pọ̀ lọ́dọọdún. Nípa ìlọsíwájú ohun àmúgbòòrò omi àti ìṣàkóso omi alálòpẹ́, a lè rí i pé gbogbo ènìyàn ní omi tí ó mọ́.", French: "L'accès à l'eau potable est un droit humain fondamental, pourtant des millions de personnes en sont privées. L'eau contaminée provoque des maladies évitables et d'innombrables décès chaque année. En améliorant les infrastructures et en soutenant une gestion durable de l'eau, nous pouvons garantir une eau sûre pour tous." },
};

export default STORIES;
