// The three long paragraphs behind the landing page's About Us / Mission /
// Vision tabs. These are longer variants of the About page copy, so they need
// their own entries.
export const TABS = {
  "Speed Foundation exists because nigeria's land, water, and people are quietly asking for help. Across the country, climate change, pollution, environmental loss, and water scarcity are threatening lives and livelihoods. We believe caring for nigeria's environment is a shared responsibility to today's communities and future generations. Driven by compassion and urgency, we restore ecosystems and protect the land and water people depend on. Through reforestation, water conservation, and climate-resilient solutions, we help communities adapt and endure. At Speed Foundation, we are nurturing a healthier, more resilient nigeria—together.": {
    Igbo: "Speed Foundation dị n'ihi na ala, mmiri, na ndị mmadụ nke Naijirịa na-arịọ enyemaka n'ụzọ jụụ. N'ofe mba a, mgbanwe ihu igwe, mmetọ, mfu gburugburu, na ụkọ mmiri na-eyi ndụ na ụzọ ibi ndụ egwu. Anyị kwenyere na ilekọta gburugburu Naijirịa bụ ọrụ anyị niile nwere maka obodo taa na ọgbọ na-abịa. Site n'ọmịiko na ngwa ngwa, anyị na-eweghachi usoro ndụ ma na-echekwa ala na mmiri ndị mmadụ dabere na ha. Site n'ịkụ osisi, nchekwa mmiri, na ngwọta na-eguzogide ihu igwe, anyị na-enyere obodo aka ime mgbanwe ma guzogide. Na Speed Foundation, anyị na-azụlite Naijirịa ahụ ike, nke siri ike — ọnụ.",
    Yoruba: "Speed Foundation wà nítorí pé ilẹ̀, omi, àti àwọn ènìyàn Nàìjíríà ń bèèrè ìrànlọ́wọ́ ní ìdákẹ́jẹ́ẹ́. Ní gbogbo orílẹ̀-èdè náà, ìyípadà ojú-ọjọ́, ìdọ̀tí, ìparun àyíká, àti àìtó omi ń halẹ̀ mọ́ ẹ̀mí àti ọ̀nà ìgbésí ayé. A gbàgbọ́ pé ìtọ́jú àyíká Nàìjíríà jẹ́ ojúṣe gbogbo wa fún àwọn àdúgbò òní àti àwọn ìran ọ̀la. Pẹ̀lú àánú àti ìyára, à ń mú àyíká padà bọ̀ sípò, à sì ń dáàbò bo ilẹ̀ àti omi tí àwọn ènìyàn gbáralé. Nípasẹ̀ ìdálẹ́ igbó, ìtọ́jú omi, àti ojútùú tí ó lè faradà ojú-ọjọ́, a ń ran àwọn àdúgbò lọ́wọ́ láti bá a mu kí wọ́n sì fara dà á. Ní Speed Foundation, à ń tọ́ Nàìjíríà tí ó ní ìlera, tí ó sì lágbára — papọ̀.",
    French: "Speed Foundation existe parce que la terre, l'eau et les habitants du Nigéria appellent discrètement à l'aide. Partout dans le pays, le changement climatique, la pollution, la perte environnementale et la pénurie d'eau menacent des vies et des moyens de subsistance. Nous croyons que prendre soin de l'environnement nigérian est une responsabilité partagée envers les communautés d'aujourd'hui et les générations futures. Animés par la compassion et l'urgence, nous restaurons les écosystèmes et protégeons la terre et l'eau dont dépendent les populations. Par le reboisement, la conservation de l'eau et des solutions résilientes au climat, nous aidons les communautés à s'adapter et à tenir. Chez Speed Foundation, nous cultivons un Nigéria plus sain et plus résilient — ensemble.",
  },
  "We protect and restore ecosystems by partnering with communities, governments, and conservation groups to preserve habitats and biodiversity. We promote green, inclusive economic growth through sustainable livelihoods like eco-tourism, organic farming, and responsible forestry. Through education, outreach, and policy advocacy, we empower individuals and stakeholders to adopt sustainable practices and support environmental protection. We lead reforestation and land rehabilitation projects, advance research on innovative sustainability solutions, and tackle pollution and waste to create healthier, resilient communities for future generations.": {
    Igbo: "Anyị na-echekwa ma na-eweghachi usoro ndụ site na imekọ ọrụ na obodo, gọọmentị, na otu nchekwa iji chebe ebe obibi na ụdị ndụ dị iche iche. Anyị na-akwalite uto akụ na ụba nke gụnyere onye ọ bụla site n'ụzọ ibi ndụ na-adigide dịka njem nlegharị anya gburugburu, ọrụ ugbo okike, na nlekọta ọhịa. Site na mmụta, mkpọsa, na nkwado iwu, anyị na-enye ndị mmadụ na ndị ọrụ ike ịnabata omume na-adigide. Anyị na-eduzi ọrụ ịkụ osisi na iweghachi ala, na-akwalite nyocha na ngwọta ọhụrụ, ma na-alụso mmetọ na ahịhịa ọgụ iji mepụta obodo ahụ ike maka ọgbọ na-abịa.",
    Yoruba: "A ń dáàbò bo àti mú àyíká padà bọ̀ sípò nípa ìfọwọ́sowọ́pọ̀ pẹ̀lú àwọn àdúgbò, ìjọba, àti àwọn ẹgbẹ́ ìtọ́jú láti pa ibùgbé àti onírúurú ẹ̀dá mọ́. A ń gbé ìdàgbàsókè ọrọ̀ ajé aláwọ̀ ewé lárugẹ nípasẹ̀ ọ̀nà ìgbésí ayé alálòpẹ́ bí ìrìnàjò àyíká, àgbẹ̀ àdánidá, àti ìtọ́jú igbó. Nípasẹ̀ ẹ̀kọ́, ìtànkálẹ̀, àti ìgbéjàko ìlànà, a ń fún àwọn ènìyàn lágbára láti gba ìṣe alálòpẹ́. A ń darí iṣẹ́ ìdálẹ́ igbó àti ìtúnṣe ilẹ̀, a ń gbé ìwádìí lárugẹ, a sì ń kojú ìdọ̀tí láti dá àwọn àdúgbò tí ó ní ìlera sílẹ̀ fún àwọn ìran ọ̀la.",
    French: "Nous protégeons et restaurons les écosystèmes en travaillant avec les communautés, les gouvernements et les organisations de conservation pour préserver les habitats et la biodiversité. Nous encourageons une croissance économique verte et inclusive par des moyens de subsistance durables : écotourisme, agriculture biologique et foresterie responsable. Par l'éducation, la sensibilisation et le plaidoyer politique, nous donnons aux individus et aux parties prenantes les moyens d'adopter des pratiques durables. Nous menons des projets de reboisement et de réhabilitation des sols, faisons progresser la recherche sur des solutions innovantes et luttons contre la pollution et les déchets pour bâtir des communautés plus saines et résilientes.",
  },
  "We envision a world where communities live in harmony with nature—where economic progress does not come at the cost of environmental destruction, and where future generations inherit a planet that is resilient, diverse, and full of opportunity. Our commitment is long-term. Our approach is collaborative. And our impact is rooted in empowering people to protect the environment not just because they must—but because they understand its value to their lives, livelihoods, and future.": {
    Igbo: "Anyị na-ele anya ụwa ebe obodo na okike na-ebi n'udo — ebe ọganihu akụ na ụba anaghị abịa site na mbibi gburugburu, ebe ọgbọ na-abịa ga-eketa ụwa siri ike, dị iche iche, ma jupụta n'ohere. Nkwa anyị bụ nke ogologo oge. Ụzọ anyị bụ imekọ ọrụ ọnụ. Mmetụta anyị dabere n'inye ndị mmadụ ike ichekwa gburugburu, ọ bụghị naanị n'ihi na ha ga-eme ya — kama n'ihi na ha ghọtara uru ọ bara na ndụ ha, ụzọ ibi ndụ ha, na ọdịnihu ha.",
    Yoruba: "A ń lá àlá ayé kan níbi tí àwọn àdúgbò yóò ti gbé ní ìbágbépọ̀ pẹ̀lú ìṣẹ̀dá — níbi tí ìlọsíwájú ọrọ̀ ajé kì yóò ti wá nípasẹ̀ ìparun àyíká, àti níbi tí àwọn ìran ọ̀la yóò ti jogún ayé tí ó lágbára, tí ó ní onírúurú, tí ó sì kún fún àǹfààní. Ìfaramọ́ wa jẹ́ ti ìgbà pípẹ́. Ọ̀nà wa jẹ́ ti ìfọwọ́sowọ́pọ̀. Ipa wa sì dá lórí fífún àwọn ènìyàn lágbára láti dáàbò bo àyíká — kì í ṣe nítorí pé wọ́n gbọ́dọ̀ ṣe é nìkan, ṣùgbọ́n nítorí pé wọ́n mọ iye rẹ̀ sí ẹ̀mí, ìgbésí ayé, àti ọjọ́ iwájú wọn.",
    French: "Nous imaginons un monde où les communautés vivent en harmonie avec la nature — où le progrès économique ne se paie pas au prix de la destruction de l'environnement, et où les générations futures héritent d'une planète résiliente, diverse et pleine d'opportunités. Notre engagement est de long terme. Notre approche est collaborative. Et notre impact repose sur le fait de donner aux gens les moyens de protéger l'environnement non pas seulement parce qu'ils le doivent, mais parce qu'ils en comprennent la valeur pour leur vie, leurs moyens de subsistance et leur avenir.",
  },
};

export default TABS;
